Repository gnuboard/g6, pull requests merged in 2024-06, with the labels that each got.

#597 [fix] #595 부트스트랩 > 게시글 작성 폼 - 생성/수정 URL 조건 누락 수정
  templates/bootstrap/board/basic/write_form.html
  templates/bootstrap/board/gallery/write_form.html
Labels: bug

#599 [add] REST API > 게시글 썸네일 정보 추가
  api/v1/models/board.py
  api/v1/routers/board.py
  service/board/list_post.py
  service/board_new/board_new.py
Labels: feature

#600 fix, feat: 회원가입 및 REST API 이슈 및 오류사항 수정
  api/settings.py
  api/v1/auth/jwt.py
  api/v1/dependencies/member.py
  api/v1/models/__init__.py
  api/v1/models/auth.py
  api/v1/models/member.py
  api/v1/models/response.py
  api/v1/routers/__init__.py
  api/v1/routers/auth.py
  api/v1/routers/captcha.py
  api/v1/routers/member.py
  bbs/register.py
  core/exception.py
  core/formclass.py
  lib/common.py
  lib/dependency/dependencies.py
  lib/dependency/member.py
  lib/mail.py
  service/member_service.py
  static/js/jquery.register_form.js
  templates/basic/member/certify_email_update_form.html
  templates/basic/member/member_profile.html
  templates/basic/member/register_form.html
  templates/bootstrap/member/member_profile.html
  templates/bootstrap/member/register_form.html
Labels: bug, feature

#601 [docs] PR 템플릿 수정사항 반영
  .github/pull_request_template.md
Labels: documentation

#603 [add] REST API > 게시글 생성 후 wr_id 정보 추가 / 비회원 게시글, 댓글 관련 추가 기능 / 글목록 페이지당 항목 수 설정
  api/v1/models/board.py
  api/v1/routers/board.py
  api/v1/routers/board_new.py
  api/v1/routers/search.py
  api/v1/service/board.py
  lib/dependency/dependencies.py
  service/board/board.py
  service/board/list_post.py
  service/board/update_post.py
  service/board_new/board_new.py
  service/search/search.py
Labels: bug

#604 [fix] 파일 업로드 에러 / 쪽지 전송 에러 및 UX 개선 / QA 메일 템플릿 적용
  api/v1/routers/memo.py
  bbs/memo.py
  lib/mail.py
  service/board/board.py
  service/memo_service.py
  service/point_service.py
  templates/basic/bbs/mail_form/qa_answered_mail.html
Labels: bug

#606 [fix] REST API > 댓글 관련 오류 수정 / 누락된 기능 추가
  api/v1/models/board.py
  api/v1/routers/board.py
Labels: bug

#613 fix: REST API > 회원정보 조회 변경 및 오류 2건 수정
  api/v1/models/member.py
  api/v1/routers/member.py
  core/models.py
  core/routers.py
Labels: bug
